# Generated by Django 3.0.8 on 2020-07-07 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 46, 13, 481256), verbose_name='date published'),
        ),
    ]
